# Generated by Django 5.1.4 on 2025-01-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_actor_review_director_review_running_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster',
            field=models.FileField(blank=True, upload_to='templates/poster/'),
        ),
    ]
