# Generated by Django 5.1.4 on 2025-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('act', '액션'), ('dra', '드라마'), ('roco', '로맨스/코미디'), ('sf', 'SF'), ('hor', '스릴러'), ('ani', '애니메이션')], default='dra', max_length=20),
        ),
    ]
