# Generated by Django 5.1.4 on 2025-01-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='아이디어명')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y%m%d', verbose_name='Image')),
                ('explain', models.TextField(verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(verbose_name='아이디어 관심도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정시간')),
                ('is_like', models.BooleanField(default=False)),
                ('develop_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool', verbose_name='예상 개발툴')),
            ],
        ),
    ]
