# Generated by Django 5.1.4 on 2025-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='아이디어명')),
                ('image', models.ImageField(blank=True, upload_to='ideas/%y%m%d', verbose_name='Image')),
                ('explain', models.TextField(verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(verbose_name='아이디어 관심도')),
                ('develop_tool', models.CharField(max_length=20, verbose_name='예상 개발툴')),
            ],
        ),
    ]
