# Generated by Django 5.1.4 on 2025-01-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_idea_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정시간'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(verbose_name='최초 등록시간'),
        ),
    ]
