# Generated by Django 5.1.4 on 2025-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_idea_updated_at_alter_idea_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
